### ISSUE TITLE
Production.js doesn't work

### ISSUE THREAD

**Issue by greygatch** [DigitalKwarts/react-server-render-example#1]
Error: Cannot find module '/Users/evangatchell/code/react-server-render-example/static/server.js'

**Comment by greygatch** [comment]
Is there an example that you know of that works?

**Comment by anrw** [comment]
Hi @greygatch,

You need to build app firstly by running: `NODE_ENV=production webpack --config webpack.production.config.js --progress --profile --colors`, which will create required `static/server.js`file. Then you will be able to run app by typing: `node production.js`. The example will be available at: http://localhost:3000/

For more reference you can read full article here: https://blog.digitalkwarts.com/server-side-rendering-with-reactjs-react-router-v4-react-helmet-and-css-modules/

Feel free to reopen if you face any issues.
