### ISSUE TITLE
Running the app from server side

### ISSUE THREAD

**Issue by rkrishn** [DigitalKwarts/react-server-render-example#4]
TypeError: serverRenderer is not a function in server.jsx could you tell me how to run the app from server

**Comment by amerllica** [comment]
Hi @rkrishn ,

You need to build app firstly by running: `NODE_ENV=production webpack --config webpack.production.config.js --progress --profile --colors`, which will create required `static/server.js` file. Then you will be able to run app by typing: `node production.js`. The example will be available at: http://localhost:3000/

For more reference you can read full article [HERE](https://blog.digitalkwarts.com/server-side-rendering-with-reactjs-react-router-v4-react-helmet-and-css-modules/)
