### ISSUE TITLE
Production Error / Webpack

### ISSUE THREAD

**Issue by gHashTag** [DigitalKwarts/react-server-render-example#6]
NODE_ENV=production webpack --config webpack.production.config.js --progress --profile --colors                             
The CLI moved into a separate package: webpack-cli

View details:
https://gist.github.com/gHashTag/0d154fb3f454a01ec28aec38f85faef2

**Comment by amerllica** [comment]
See the [#2](https://github.com/DigitalKwarts/react-server-render-example/issues/2) issue,
